@baseUrl = http://localhost:8080

### Get all rooms
GET {{baseUrl}}/rooms
Accept: application/json

### Get all rooms by like number
GET {{baseUrl}}/rooms?number=10
Accept: application/json

### Get all rooms by exact status
GET {{baseUrl}}/rooms?currentStatus=DISPONIBLE
Accept: application/json

### Get all rooms by exact category
GET {{baseUrl}}/rooms?category=STANDARD
Accept: application/json

### Change room status
PUT {{baseUrl}}/rooms/1/status
Content-Type: application/json

{
  "employeeId": 1,
  "newStatus": "DISPONIBLE"
}
