spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:imperial_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
  h2:
    console:
      enabled: false
