spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:imperial_database}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:1234}
  h2:
    console:
      enabled: false
