# ===============================
# 🚀 application-prod.yml (deploy)
# ===============================
spring:

  jpa:
    hibernate:
      ddl-auto: none        # No altera el esquema en producción
    show-sql: false         # Evita logs de SQL

  datasource:
    # Ajustes del pool de conexiones para producción (HikariCP por defecto en Spring Boot)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariPoolProd